import com.spring.practice.model.SimpleCollectionHolder;
import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    private static Logger log = Logger.getLogger(App.class);


    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("META-INF/application-context.xml");
        SimpleCollectionHolder simpleCollectionHolder = applicationContext.getBean("simpleCollectionHolderId", SimpleCollectionHolder.class);
        log.info("========printing injected list============");
        List<String> list = simpleCollectionHolder.getList();
        for (String s : list) {
            log.info(s);
        }
        log.info("========printing injected set============");
        Set<String> set = simpleCollectionHolder.getSet();
        for (String s : set) {
            log.info(s);
        }
        log.info("========printing injected map============");
        Map<String, String> map = simpleCollectionHolder.getMap();
        for (Map.Entry<String, String> entry : map.entrySet()) {
            log.info("key : " + entry.getKey() + " value :" + entry.getValue());
        }
        ((ClassPathXmlApplicationContext) applicationContext).close();

    }
}
