import com.spring.practice.model.Student;
import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static Logger log = Logger.getLogger(App.class);


    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("META-INF/application-context.xml");
        Student student = applicationContext.getBean("studentId", Student.class);
        log.info(student.toString());

        ((ClassPathXmlApplicationContext) applicationContext).close();


    }
}
