import com.spring.practice.model.PrototypeBean;
import com.spring.practice.model.Student;
import com.spring.practice.model.Subject;
import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static Logger log = Logger.getLogger(App.class);


    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("META-INF/application-context.xml");
        Student student = applicationContext.getBean("studentId", Student.class);
        log.info(student.toString());

        PrototypeBean prototypeBean1=applicationContext.getBean("prototypeBanId",PrototypeBean.class);
        PrototypeBean prototypeBean2=applicationContext.getBean("prototypeBanId",PrototypeBean.class);
        log.info("prototypeBean1==prototypeBean2"+(prototypeBean1==prototypeBean2));

        ((ClassPathXmlApplicationContext) applicationContext).close();


    }
}
